server:
  host: localhost
  port: 8080
  poolSize: 8
  minThreads: 8
  maxThreads: 200
  idleTimeout: 5000

database:
  driverClass: org.h2.Driver
  user: user
  password: pass
  url: jdbc:h2:mem:test
